"use client";

import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, CheckSquare, Download, Copy, Share2, Loader2, Printer } from "lucide-react";
import { Button } from "./ui/Button";
import { showSuccess, showError } from "@/lib/toast";
import { exportToPdf } from "@/lib/pdf-export"; // Assuming this utility exists/works

interface ShoppingList {
    categories: {
        name: string;
        items: string[];
    }[];
}

interface ShoppingListModalProps {
    isOpen: boolean;
    onClose: () => void;
    list: ShoppingList | null;
    title?: string;
}

export function ShoppingListModal({ isOpen, onClose, list, title = "Shopping List" }: ShoppingListModalProps) {
    const contentRef = useRef<HTMLDivElement>(null);
    const [isExporting, setIsExporting] = useState(false);

    if (!list) return null;

    const handleCopy = async () => {
        const text = list.categories.map(cat =>
            `${cat.name}:\n${cat.items.map(item => `- ${item}`).join('\n')}`
        ).join('\n\n');

        try {
            await navigator.clipboard.writeText(text);
            showSuccess("List copied to clipboard!");
        } catch (err) {
            showError("Failed to copy list.");
        }
    };

    const handleExport = async () => {
        if (!contentRef.current) return;
        setIsExporting(true);
        try {
            await exportToPdf(contentRef.current, "Shopping_List");
            showSuccess("PDF downloaded!");
        } catch (err) {
            showError("Failed to generate PDF.");
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <motion.div
                        initial={{ scale: 0.95, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        exit={{ scale: 0.95, opacity: 0 }}
                        className="glass-card w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
                    >
                        {/* Header */}
                        <div className="p-4 border-b border-slate-200 dark:border-white/10 flex justify-between items-center bg-slate-50 dark:bg-slate-800/50">
                            <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                                <CheckSquare className="w-5 h-5 text-green-500" />
                                {title}
                            </h3>
                            <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-white">
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        {/* List Content */}
                        <div className="flex-1 overflow-y-auto p-6 bg-white dark:bg-slate-900">
                            <div ref={contentRef} className="space-y-6 text-slate-900 dark:text-slate-100">
                                <div className="hidden print:block mb-4 text-center">
                                    <h1 className="text-2xl font-bold">{title}</h1>
                                    <p className="text-sm text-slate-500">Generated by Decision Jar</p>
                                </div>
                                {list.categories.map((cat, idx) => (
                                    <div key={idx} className="space-y-2 break-inside-avoid pdf-item">
                                        <h4 className="font-bold text-green-600 dark:text-green-400 uppercase tracking-wider text-xs border-b border-green-100 dark:border-green-500/20 pb-1">
                                            {cat.name}
                                        </h4>
                                        <ul className="space-y-1">
                                            {cat.items.map((item, i) => (
                                                <li key={i} className="flex items-start gap-2 text-sm">
                                                    <span className="w-1.5 h-1.5 bg-slate-300 rounded-full mt-1.5 shrink-0" />
                                                    <span className="leading-relaxed">{item}</span>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="p-4 border-t border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-slate-800/50 flex gap-2">
                            <Button variant="outline" onClick={handleCopy} className="flex-1">
                                <Copy className="w-4 h-4 mr-2" /> Copy
                            </Button>
                            <Button onClick={handleExport} disabled={isExporting} className="flex-1">
                                {isExporting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Download className="w-4 h-4 mr-2" />}
                                Export PDF
                            </Button>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
