/**
 * Demo Mode - Pre-populated data for new users to explore
 */

export const DEMO_IDEAS = [
    {
        id: 'demo-1',
        description: 'Pizza Night at Mario\'s',
        category: 'MEAL',
        cost: '$$',
        duration: 2,
        indoor: true,
        activityLevel: 'LOW',
        timeOfDay: 'EVENING',
        details: 'Try their famous wood-fired margherita pizza',
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-2',
        description: 'Movie Marathon at Home',
        category: 'ACTIVITY',
        cost: 'FREE',
        duration: 4,
        indoor: true,
        activityLevel: 'LOW',
        timeOfDay: 'EVENING',
        details: 'Cozy night in with popcorn and your favorite films',
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-3',
        description: 'Morning Jog in the Park',
        category: 'ACTIVITY',
        cost: 'FREE',
        duration: 1,
        indoor: false,
        activityLevel: 'HIGH',
        timeOfDay: 'MORNING',
        details: 'Get energized with a sunrise run through nature',
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-4',
        description: 'Paint and Sip Class',
        category: 'EVENT',
        cost: '$$$',
        duration: 3,
        indoor: true,
        activityLevel: 'LOW',
        timeOfDay: 'EVENING',
        details: 'Unleash your creativity with art and wine',
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-5',
        description: 'Board Game Tournament',
        category: 'ACTIVITY',
        cost: 'FREE',
        duration: 3,
        indoor: true,
        activityLevel: 'LOW',
        timeOfDay: 'EVENING',
        details: 'Battle it out with classic and modern board games',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-6',
        description: 'Cook a New Recipe Together',
        category: 'MEAL',
        cost: '$$',
        duration: 2,
        indoor: true,
        activityLevel: 'MEDIUM',
        timeOfDay: 'EVENING',
        details: 'Try making homemade pasta from scratch',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-7',
        description: 'Photo Walk Downtown',
        category: 'ACTIVITY',
        cost: 'FREE',
        duration: 2,
        indoor: false,
        activityLevel: 'MEDIUM',
        timeOfDay: 'AFTERNOON',
        details: 'Capture the city\'s beauty through your lens',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-8',
        description: 'Sunset Yoga Session',
        category: 'ACTIVITY',
        cost: '$',
        duration: 1,
        indoor: false,
        activityLevel: 'MEDIUM',
        timeOfDay: 'EVENING',
        details: 'Find your zen as the sun goes down',
        createdAt: new Date().toISOString(),
    },
];

export const DEMO_MEMORIES = [
    {
        id: 'demo-mem-1',
        description: 'Stargazing Picnic',
        category: 'ACTIVITY',
        cost: '$',
        duration: 3,
        indoor: false,
        activityLevel: 'LOW',
        timeOfDay: 'EVENING',
        selectedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        selectedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        rating: 5,
        notes: 'Perfect weather! Saw 3 shooting stars 🌠',
    },
    {
        id: 'demo-mem-2',
        description: 'Sushi Making Class',
        category: 'MEAL',
        cost: '$$$',
        duration: 2,
        indoor: true,
        activityLevel: 'MEDIUM',
        timeOfDay: 'EVENING',
        selectedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        selectedDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        rating: 4,
        notes: 'So much fun! The instructor was hilarious',
    },
];

export const DEMO_JAR = {
    id: 'demo-jar',
    name: '✨ Demo Jar',
    topic: 'DATING',
    isPrivate: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

export const DEMO_USER = {
    id: 'demo-user',
    name: 'Demo User',
    email: 'demo@example.com',
    isDemo: true,
    isPremium: false,
};

export const DEMO_LIMITS = {
    AI_REQUESTS: 2,
    WEEKEND_PLANS: 1,
    CONCIERGE_USES: 1, // Allow one premium concierge trial
    MAX_IDEAS: 50,
    MAX_JARS: 1,
};

