-- Add streak tracking fields to Jar table
ALTER TABLE "Jar" ADD COLUMN IF NOT EXISTS "lastActiveDate" TIMESTAMP(3);
ALTER TABLE "Jar" ADD COLUMN IF NOT EXISTS "currentStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Jar" ADD COLUMN IF NOT EXISTS "longestStreak" INTEGER NOT NULL DEFAULT 0;
